### ISSUE TITLE
Add array support in query string parameters

### ISSUE THREAD

**Issue by romusz** [gilt/apidoc#208]
Play supports an automatic aggregation of values with the same param name. That is a request `http://localhost:9000/tests?id=1&id=2&id=3` can be received by Play route: 
```
GET /tests controllers.Test.get(id: List[Long])
```
and mapped to controller:

```scala
object Tests
extends Controller {
  def get(ids: List[Long]) = Action {
    Ok(ids.mkString("[", ", ", "]"))
  }
}
```

But current apidoc generates the following route:
```
GET     /tests     controllers.Tests.get()
# Additional parameters to GET /tests
#   - id: Seq[Long]
```

for such resource in api.json
```
...
  "resources": {
    "test": {
      "operations": [
        {
          "method": "GET",
          "path": "/",
          "parameters": [
            {
              "name": "id",
              "type": "[long]",
            },
...
```

**Comment by sthomp** [comment]
+1 I am currently working around this

**Comment by infomofo** [comment]
+1 right now without support for array parameters we're encouraging some pretty poor api practices which i'm starting to see in a lot of apidocs- unnecessary containment, or passing arrays around intentionally as strings

**Comment by sthomp** [comment]
It seems like there is a bug related to this as well. If I have the following api.json:

```
          "method": "GET",
          "description": "Get all the feedback that a user has given for specific product look ids",
          "path": "/:user_guid",
          "parameters": [
            {
              "name": "product_look_ids",
              "type": "[long]",
              "required": false,
              "description": "Optionally, you can filter the results to a specific list of product_look_ids. If you specify just a single product_look_id the performance will be faster."
            }
          ],
          "responses": {
            "200": {
              "type": "[feedback]"
            }
          }
```

Then the Client will generate:

```
        val queryParameters = productLookIds.map("product_look_ids" -> _.toString)
```

This will generate a list of query params that all have the same key. So that only the last element in the list is actually sent.

For example, if I pass in:
```
      val productLookIds: Seq[Long] = Seq(123l, 456l, 789l)
```

This will generate:
```
List((product_look_ids,123), (product_look_ids,456), (product_look_ids,789))
```

And on the server it will only receive the last element:
```
Some(789)
```

**Comment by sthomp** [comment]
The work around for now is to use a comma delimited string

**Comment by romusz** [comment]
tested today with ning and play-based generated clients. works for me. the only thing needed is to manually edit the route (as shown at the top), but both clients work out-of-the-box with multiple values of the same query parameter.

**Comment by sthomp** [comment]
Thanks, Ill have to try this again. But Im hesitant to modify the routes file since it will cause confusion in the future if we need to modify api.json.

**Comment by romusz** [comment]
agreed. i like to c/p the whole routes file. with the hack i need to let the whole team know to patch it every time they c/p routes.

**Comment by mbryzek** [comment]
pull request for array support at:
  https://github.com/gilt/apidoc-generator/pull/2

**Comment by mbryzek** [comment]
Merged in Feb 2015
