### ISSUE TITLE
Support for sum types / algebraic data types

### ISSUE THREAD

**Issue by romusz** [gilt/apidoc#222]
Each value type would be defined by a JSON object and contain a common `tag` field of its type.
ADTs would map to sealed case class hierarchies in Scala.

**Comment by romusz** [comment]
Hopefully, not too late for my comment - wrote it earlier but not submitted:
My concern with the above example is that it models disjoint types (co-products) rather then sum types. In Scala, in order to have a function accepting or returning a value of this type it would need to be expressed as (1) `Either[Either[FooA, FooB], FooC]` or (2) we'd leak `Wrapper` out or (3) we'd resign ourselves to `Any`.

If we, however, use a sealed case class hierarchy (the Scala's idiomatic way of expressing algebraic data types), things will be more pleasant to work with:
```
sealed abstract class Foo
case class FooA(one: String) extends Foo
case class FooB(two: Int) extends Foo
case class FooC(three: Boolean) extends Foo
```

This will also make serialization simpler, as there's not need for a wrapper:
```
    implicit val reads: Reads[Foo]  =
      {
        (__ \ "foo_a").read[models.FooA]
      } orElse {
        (__ \ "foo_b").read[models.FooB]
      } orElse {
        (__ \ "foo_c").read[models.FooC]
      }

    implicit val writes = new Writes[Foo] {
      def writes(foo: Foo) = {
        val pair = foo match {
          case f: FooA => "foo_a" -> formatFooA.writes(f)
          case FooB(x) => "foo_b" -> formatFooB.writes(x)
          case FooC(x) => "foo_c" -> formatFooC.writes(x)
        }
        JsObject(pair::Nil)
      }
    }
```

Sum types could be expressed in api.json similarly to enums as
```
"unions": {
  "foo": {
    "description": "foos",
    "values": [
      { "foo_a": [ { "name": "one", "type": "string" } ] },
      { "foo_b": [ { "name": "two", "type": "int" } ] },
      { "foo_c": [ { "name": "three", "type": "boolean" } ] }
    ]
  }
}
```

Primitive types would need to wrapped by developer - but that's a good thing as for me as it would add (semantic) types to those values. String or Int to me are just data representation not a value type (e.g., a String can be username or plain-text password or password hash, the compiler has nothing to work with to catch swapped parameter errors).

**Comment by mbryzek** [comment]
Thanks paul - I've done a bunch of work to enable support for union types on the branch:

222-union-types

There's still a lot to do, but essentially I'm hoping to support this syntax in api.json:

"type": "string | boolean | long"

including support for primitive types. Trying to get this branch to a first milestone to be able to deploy with a more flexible type implementation, then will need to iterate on actual implementations for ruby and scala clients

**Comment by romusz** [comment]
yes, I've seen the work is well under way, that's why my I've thought comment might have been too late.
I've seen the new api.json syntax to support this feature and while it's concise it's doesn't allow for any descriptions of each cases (e.g, when is the value of type string or boolean or long and what does it mean) and the type "name" may be long if there are several cases to cover. If we define a separate sum type we can have room for descriptions and at use site the type name will be short (and following the same pattern as a built-in types and custom enums we have now).

Also have you decided on Scala representation of it? Each of the three ways I described above are not great.

**Comment by mbryzek** [comment]
"order": {
  "fields": [
    { "name": "user", "type": "registered | guest | uuid" }
  ]
}

==> would result in a nasty generated name that would be exposed to
    the user. This is not nice.

fixed uuid(16); -- creates a type named 'uuid' that is a 16 byte value
  ==> Ignore fixed types for now

"unions": {
  "user": {
    "types": [
      { "name": "registered", "description": "optional..." },
      { "name": "guest" },
      { "name": "uuid" }
    ]
  },
  "person": {
    "types": [
      { "name": "registered", "description": "optional..." },
      { "name": "guest" },
      { "name": "uuid" }
    ]
  }
}

sealed trait User
sealed trait Person

case class Registered {
  guid: uuid,
  email: string
}

case class Guest {
  guid: uuid
} extends User

object User {

  case class Uuid(value: _root_.java.util.UUID)

  case class String(value: _root_.java.lang.String)

  case class Int(value: _root_.java.lang.String)

  // Make LongType if needed
  case class Long(value: _root_.java.lang.String)

}

**Comment by mbryzek** [comment]
Progress so far : https://github.com/gilt/apidoc-generator/tree/master/example-union-types

**Comment by mbryzek** [comment]
released!
