### ISSUE TITLE
Refactor FailedRequest

### ISSUE THREAD

**Issue by haywood** [gilt/apidoc#266]
I think that FailedRequest should be refactored into a class that takes just a status code and a body:

    case class FailedRequest(status: Int, body: String) extends Exception(status + ": " + body)

This class is generic and remains the same between the Ning and Play clients. It also makes it easy to get to the response code and body separately. Additionally it is serializable, where the existing version is not. This matters, because it causes ugly and confusing stack traces in scalatest. While this is really an issue with the framework it is unclear if and when it will be fixed.

**Comment by mbryzek** [comment]
FYI: implemented on the 222-union-types branch

**Comment by mbryzek** [comment]
released
