### ISSUE TITLE
Styling issue on nav bar

### ISSUE THREAD

**Issue by jkenny** [gilt/apidoc#269]
The "documentation" link is shifted to the left and half hidden.
![screen shot 2015-01-10 at 10 37 32](https://cloud.githubusercontent.com/assets/1324338/5691254/dfd30ab4-98b4-11e4-8adc-384ccdac21aa.png)

**Comment by mbryzek** [comment]
odd - I can replicate if I really zoom out in the browser. does problem fix if you zoom in a bit?

**Comment by dallasgutauckis** [comment]
To 125%, yes.

**Comment by mbryzek** [comment]
odd - thanks! we have a big release going out this week which hopefully fixes this - should be deployed by end of week and would love to know if the problem still exists.

**Comment by mbryzek** [comment]
This should be fixed now (I hope!) have a new problem that the apidoc logo itself is now hidden,but will fix in another patch
