### ISSUE TITLE
Support different versions of api.json

### ISSUE THREAD

**Issue by haywood** [gilt/apidoc#27]
api.json:
{
  "schema": "0.0.1",
  "base_uri": "http://www.example.com",
  "models": { ... },
  "resources": [ ... ]
}

**Comment by mbryzek** [comment]
With the introduction of the service spec in the 0.8.x release of apidoc - we have versioning supported of service.json - see www.apidoc.me/gilt/apidoc-spec - internally we store the latest service.json - and automatically upgrade any existing services
