### ISSUE TITLE
ordering of tags by creation or last update time

### ISSUE THREAD

**Issue by brazir** [gilt/apidoc#271]
It would be nice to have the tags sorted by creation or last update time or ideally have proper support for snapshotting.  Currently they are all sorted alphabetically and the released version will always be before the snapshot.
![screen shot 2015-01-20 at 3 05 35 pm](https://cloud.githubusercontent.com/assets/247430/5825170/51fc867e-a0b7-11e4-8048-69ff2c666331.png)

**Comment by mbryzek** [comment]
interesting - I on

**Comment by mbryzek** [comment]
interesting - we could also reverse the sort so the non dev version of any major/minor/micro comes first
