### ISSUE TITLE
Getting another error uploading an api.json

### ISSUE THREAD

**Issue by infomofo** [gilt/apidoc#276]
Created by: https://gist.github.com/infomofo/566f3ddb05d61acd46c9
![screen shot 2015-01-29 at 12 45 06 pm](https://cloud.githubusercontent.com/assets/539599/5962851/b6d24bca-a7b4-11e4-92a3-c0f1c3dfe093.png)

**Comment by mbryzek** [comment]
We were missing validation of default values when used in operation parameters. This has been fixed on the 222-union-types branch where we had overhauled validation. Will go live once that branch is released

**Comment by mbryzek** [comment]
Released
