### ISSUE TITLE
Backwards compatibility of union types

### ISSUE THREAD

**Issue by andreyk0** [gilt/apidoc#279]
Similar problem to 'enums', do we need some 'catch all' 
   case class Unknown(unionType: String)
union member auto-generated for each type?

This forces clients to think about forward compatibility (need to handle this case in all 'match' statements).
It also allows one to write more future-proof code in some places.
E.g. something like { def foo(u: User): Option[AdminUser] } can be written to be future proof wrt to any changes of User 'union' type that preserve AdminUser.

The alternative is to always deal with runtime exceptions.

**Comment by mbryzek** [comment]
See: https://github.com/gilt/apidoc-generator/commit/90a47fa1a994d20e621972ed2d8da9e2917242ca
