### ISSUE TITLE
The Ning client starts too many thread pools

### ISSUE THREAD

**Issue by haywood** [gilt/apidoc#280]
Every time a client instance is created it starts a new cached thread pool instance. When running tests in another project I observed OOMs as a result. I propose that the generated client for Ning come with a default singleton thread pool, and allow client overrides in the constructor.

**Comment by emersonloureiro** [comment]
This has actually been a problem in production for me. Unfortunately, I had to create multiple clients of my service - for sending authentication via cookie - and didn't realize that under the hood one it was also instantiating one ```AsyncHttpClient```. Needless to say, this approach starved the machine from resources - it couldn't create more threads.

**Comment by mbryzek** [comment]
fixed in 0.8 release which should be online next week
