### ISSUE TITLE
Support for 22+ fields in JSON reads/writes in Play 2.3 client

### ISSUE THREAD

**Issue by kiambogo** [gilt/apidoc#285]
Currently if a defined case class has more than 21 fields, the JSON reads/writes will not compile. Before Scala 2.11, there was an arity limit of 21 fields in a case class; this was changed to allow for N fields in 2.11. Can the code generator for Scala Play clients leverage a Read/Write builder in some fashion (http://stackoverflow.com/questions/27301131/writes-for-json-views-with-more-than-21-fields-in-play-2-3) to allow for more than 21 fields?

**Comment by mbryzek** [comment]
I might be mis-remembering, but unfortunately the field limit still exists in play json - e.g. we did retry expanded field support in the client following scala 2.11 release, but unfortunately the libraries we use do not yet fully support this.

**Comment by adrianmaurer** [comment]
is this still the case?
