### ISSUE TITLE
An apidoc resource with slightly different error response types will generate invalid scala

### ISSUE THREAD

**Issue by infomofo** [gilt/apidoc#290]
I have an apidoc with a resource with the following responses:

    responses: {
    200: {
    type: "user",
    description: "the addressed user id was successfully replaced"
    },
    201: {
    type: "user",
    description: "a user was created with this id"
    },
    400: {
    type: "[string]",
    description: "This request was malformed"
    },
    401: {
    type: "string",
    description: "The user being modified does not match the user name of the authorized user in     the header"
    }
    }

This is accepted by the apidoc site as valid apidoc. However the scala generator includes the following:

    package error {

    import codalytic.models.json._

    case class ValueResponse(
      response: play.api.libs.ws.WSResponse,
      message: Option[String] = None
    ) extends Exception(message.getOrElse(response.status + ": " + response.body)){
      import codalytic.models.json._
      lazy val value = response.json.as[Seq[String]]
    }
    }

    package error {

    import codalytic.models.json._

    case class ValueResponse(
      response: play.api.libs.ws.WSResponse,
      message: Option[String] = None
    ) extends Exception(message.getOrElse(response.status + ": " + response.body)){
      import codalytic.models.json._
      lazy val value = response.json.as[String]
    }
    }

which is invalid scala.

The original api.json that generated this issue is in this gist: https://gist.github.com/infomofo/ed0372afa7d872f755a2

The offending endpoint is 

    PUT users/:username

**Comment by mbryzek** [comment]
Thanks for posting! This was already actually already fixed on master - will be available online soon (next few days). The actual code from master looks like:

          case r if r.status == 400 => throw new com.gilt.codalytic.v0.errors.ValuesResponse(r)
          case r if r.status == 401 => throw new com.gilt.codalytic.v0.errors.ValueResponse(r)

**Comment by mbryzek** [comment]
Released
