### ISSUE TITLE
Add validation errors for unrecognized JSON property names in api.json

### ISSUE THREAD

**Issue by ecwall** [gilt/apidoc#292]
While defining my resources, I mistyped the "responses" property as "response" like so
"resources": {
    "bonus": {
      "path": "/bonuses",
      "operations": [
        {
          "method": "GET",
          "path": "/:id",
          **"response"**: {
            "200": { "type": "bonus" },
            "400": { "type": "error" }
...

The result was that the generated client returned a Future[Unit] instead of Future[Bonus].  

I think it would be helpful if any unrecognized properties would cause a validation error instead of being ignored.  It would be even more helpful if the validation error message contained the acceptable properties depending on the context (here it would list "method", "path", "responses", ...)

**Comment by mbryzek** [comment]
Also would be nice to validate when the type is wrong - so when models, resources or responses are arrays instead of maps

**Comment by chrhicks** [comment]
+1!!
