### ISSUE TITLE
per-project visibility broken

### ISSUE THREAD

**Issue by haywood** [gilt/apidoc#294]
Setting a project to visibility only at organization-level does not work. Example: [this version](http://www.apidoc.me/gilt/iris-hub/77-purchase-cancellation-event) is set to organization, but is visible publicly.

**Comment by mbryzek** [comment]
can you give me a bit more information? When I access http://www.apidoc.me/gilt/iris-hub - I am allowed access from my gilt account but denied when not logged in or from a non gilt account.

Example:

$ curl -I http://www.apidoc.me/gilt/iris-hub/latest
HTTP/1.1 303 See Other
