### ISSUE TITLE
Map type only supports singletons - would like to have a Map[Seq[String]]

### ISSUE THREAD

**Issue by mbryzek** [gilt/apidoc#295]
would like: Map(String, Seq[Long])
tried creating a separate model of Seq[Long] but then would require it to be an json object.

this is an existing svc w/ one endpoint that doesn't have client.  thought i'd just use apidoc to create a client/interface.

**Comment by haywood** [comment]
+1 this

In general, I'd like to have support for maps and arrays containing arbitrary types. Willing to implement... For scala code generation I believe this is a straightforward change, as it just means slightly expanding the types of things that can be contained in a ScalaDatatype.List or a ScalaDatatype.Map.

**Comment by mbryzek** [comment]
+1 to idea - would love the help in code!

also this related request came in today: https://github.com/gilt/apidoc/issues/323

**Comment by mbryzek** [comment]
@haywood added support for this - in production
