### ISSUE TITLE
Latest version for an api shows snapshots first.

### ISSUE THREAD

**Issue by rcaloras** [gilt/apidoc#301]
Should we actually be showing the snapshot version first here or should we be showing the releases? We may be able to simply sort based on the most recently uploaded one? Related to https://github.com/gilt/apidoc/issues/300

![image](https://cloud.githubusercontent.com/assets/149818/6622218/cbdaf706-c8b1-11e4-8c8a-a73eeec6179a.png)

**Comment by mbryzek** [comment]
releasing the feature to delete versions - once released you can delete the 77-xxx and 79-xxx versions and things will be back to normal
