### ISSUE TITLE
Difficult to debug Union types

### ISSUE THREAD

**Issue by rlmartin** [gilt/apidoc#312]
Because the jsonReadsXXX implicit method waterfalls through the union type options using orElse, it essentially "matches" on the first successful parsing. Conversely, when it fails, it will show the failure of the last class in the waterfall - not the one called out by the classname in the json. This makes debugging difficult, since you will have no idea which json properties are missing (unless the class you care about is the last one in the waterfall).

MReed is thinking the fold method here (https://www.playframework.com/documentation/2.3.x/api/scala/index.html#play.api.libs.json.JsResult) could be a solution here.

**Comment by haywood** [comment]
Actually, an even better approach is probably to look for each key in turn, and commit to parsing the appropriate class if one of the known keys is present. If none of the known keys is there, then a validation error indicating this should be returned.

What I was thinking with the fold solution was to collect the errors as each alternative was tried, but I think the above is much more straightforward.

**Comment by rlmartin** [comment]
I agree with the above.

**Comment by haywood** [comment]
This issue has been raise [here](https://github.com/gilt/apidoc-generator/issues/15)
