### ISSUE TITLE
Requirement on specifying the apidoc version in api.json

### ISSUE THREAD

**Issue by kiambogo** [gilt/apidoc#322]
With apidoc 0.9.5 comes the requirement to explicitly state which version of apidoc your api.json is meant for. While I can see the useful nature of this change as it ensures that the uploader is aware of the changes to apidoc and can avoid breaking changes as apidoc evolves, I think needing to specify this would seem strange to a newcomer. Perhaps it could be an optional field, where if not specified it uses the latest version of apidoc? Breaking changes in the future can then be handled by updating the api.json to match the new model, or by specifying the previous version of apidoc.

**Comment by mbryzek** [comment]
agreed - I like idea of making optional - will take a look

**Comment by mbryzek** [comment]
Have released the change to default the apidoc version to the latest.
