### ISSUE TITLE
Have code upload actually report generation problems

### ISSUE THREAD

**Issue by Seanstoppable** [gilt/apidoc#326]
Currently just get a play error page. Not really sure if the problem is with the app or with my apidoc. Making this clear, and showing validation error if they are not bubbling up would eliminate confusion/allow users to debug.

**Comment by mbryzek** [comment]
mind posting a link to the generator causing an issue?

**Comment by Seanstoppable** [comment]
Here is the gist of the apidoc I was trying to upload:

https://gist.github.com/Seanstoppable/5b292e6be08c8aa2f6df
