### ISSUE TITLE
Generator is throwing an error in production, while works for the same project when running apidoc + generators locally

### ISSUE THREAD

**Issue by kiambogo** [gilt/apidoc#336]
Error id: 6m9bdol0o

**Comment by mbryzek** [comment]
Mind adding a link to your project (or attaching the api.json)?

**Comment by kiambogo** [comment]
PM'd you with the api.json file

**Comment by mbryzek** [comment]
Latest released appears to have fixed - would you mind re-opening if still a problem?

**Comment by kiambogo** [comment]
Will do - thanks!

**Comment by kiambogo** [comment]
Issue is occurring again - error id: 6mamfhhjl . Let me know if you need the api.json.
