### ISSUE TITLE
Support for map type

### ISSUE THREAD

**Issue by kiambogo** [gilt/apidoc#340]

**Comment by mbryzek** [comment]
Mind posting a bit more information on what you are looking for / trying to do?

**Comment by kiambogo** [comment]
Sorry, that was a little vague. 

The issue was created around the need to offer a mapping between two values (i.e string -> int), as a first class citizen in the apidoc types.  Upon giving this a bit more thought, the json object type is capable of fulfilling this need, albeit while sacrificing type safety.

**Comment by mbryzek** [comment]
I'm curious if you've tried to define the type using "map[integer]" - we do have a constraint that the keys must be strings, but you can define a map where the values are any known type. Do you want to give that a try? or if you have and it's not ideal / insufficient - would love to know the details.

going to close this for now - but re-open if there's something you' d like to see in apidoc

thanks!

**Comment by kiambogo** [comment]
That's exactly what I was looking for -  I would recommend updating the types documentation (http://www.apidoc.me/doc/types) perhaps to include the listing of map. Thanks!

**Comment by mbryzek** [comment]
Thanks! FYI  - for future it is documented here:

http://www.apidoc.me/doc/apiJson


   - *type* specifies the type of this field. Acceptable values include the
   name of either an enum, a model, or a (primitive type
   <http://www.apidoc.me/doc/types>). To specify a List, the type name can
   be wrapped with "[]". For example, to specify that the type is a collection
   of strings, use "[string]". To specify a Map, the type name can be prefixed
   with "map[type]". For example, to specify that the type is a collection of
   longs, use "map[long]". Note that for map, the keys must be strings (per
   the JSON specification).
