### ISSUE TITLE
Unique client identifier feature request

### ISSUE THREAD

**Issue by brazir** [gilt/apidoc#68]
Currently there is no way to tell which client a request has come from as you would have to include it in all the parameter lists.
--The generated routes should be changed to include a * which would be the client id.
--The generated clients should have a unique value inserted upon download.

This will allow for tracking client based issues.

**Comment by mbryzek** [comment]
I don't think it makes sense for apidoc to enforce this sort of pattern. Today users could inject any header they like into clients. Going to close
